25.14_ext Release

diff --git a/script/terraform/template/ansible/common/roles/docker-image/tasks/to-daemon.yaml b/script/terraform/template/ansible/common/roles/docker-image/tasks/to-daemon.yaml
--- a/script/terraform/template/ansible/common/roles/docker-image/tasks/to-daemon.yaml
+++ b/script/terraform/template/ansible/common/roles/docker-image/tasks/to-daemon.yaml
@@ -12,19 +12,24 @@
     - name: setup port forwarding
       shell:
         cmd: |
-          nohup ssh -4 -p {{ ansible_port | default(22) }} {{ ansible_user }}@{{ ansible_host }} -fNL {{ local_daemon_url }}:/var/run/docker.sock -i {{ ansible_private_key_file }} >> /tmp/{{ wl_namespace }}-ssh.logs 2>&1 &
+          nohup ssh -4 -p {{ ansible_port | default(22) }} {{ ansible_user }}@{{ ansible_host }} -fNL {{ local_daemon_url }}:/var/run/docker.sock {% if ansible_private_key_file is defined %}-i {{ ansible_private_key_file }}{% endif %} >> /tmp/{{ wl_namespace }}-ssh.logs 2>&1 &
           disown
         executable: /bin/bash
       delegate_to: localhost
-      become: false
 
     - name: inspect local images
-      command: "docker image inspect {{ item.key }}"
+      shell:
+        cmd: |
+          {% if ('/' not in workload_config.registry) or ('/' not in item.key) %}
+            docker image inspect {{ item.key }}
+          {% else %}
+            false
+          {% endif %}
+        executable: /bin/bash
       register: inspect_l
-      loop: "{{ wl_docker_images | dict2items | rejectattr('key','match',(skopeo_sut_accessible_registries|split(',')|reject('==','')|default(['NO-REGISTRY'],true)|map('regex_replace','^(.*)$','^\\1.*$')|join('|'))) }}"
+      loop: "{{ wl_docker_images | dict2items | rejectattr('key','match',(sut_accessible_registries|default(skopeo_sut_accessible_registries,true)|split(',')|reject('==','')|default(['NO-REGISTRY'],true)|map('regex_replace','^(.*)$','^\\1.*$')|join('|'))) }}"
       loop_control:
         label: "{{ item.key }}"
-      become: true
       delegate_to: localhost
       ignore_errors: true
       no_log: true
@@ -41,21 +46,8 @@
       ignore_errors: true
       no_log: true
 
-    - name: copy daemon images to daemon
-      include_tasks:
-        file: to-daemon-copy.yaml
-      when:
-      - inspect.rc == 0
-      - inspect.stdout | from_json | map(attribute='Config') | map(attribute='Labels') | map(attribute='BUILD_ID') | map('default','NB',true) | difference(inspect_r.results[inspect_idx].stdout | default('[{"Config":{"Labels":{}}}]',true) | from_json | map(attribute='Config') | map(attribute='Labels') | map(attribute='BUILD_ID') | map('default','NC',true)) | length > 0
-      loop: "{{ inspect_l.results }}"
-      loop_control:
-        loop_var: inspect
-        index_var: inspect_idx
-        label: "{{ inspect.item.key }}"
-      no_log: true
-
     - name: Inspect registry images
-      command: "skopeo inspect {{ skopeo_inspect_options }} --tls-verify={{ ((item.item.value|bool) and (item.item.key is not match('^'+(skopeo_insecure_registries|split(',')|reject('==','')|default(['NO-REGISTRY'],true)|join('|'))+'.*$'))) | ternary('true','false') }} docker://{{ item.item.key }}"
+      command: "skopeo inspect {{ skopeo_inspect_options }} --tls-verify=false docker://{{ item.item.key }}"
       environment:
         ALL_PROXY: ""
         all_proxy: ""
@@ -65,21 +57,51 @@
       loop_control:
         label: "{{ item.item.key }}"
       delegate_to: localhost
-      become: true
       ignore_errors: true
       no_log: true
 
-    - name: copy registry images to daemon
-      include_tasks:
-        file: to-daemon-copy.yaml
-      when:
-      - inspect.rc != 0
-      - ('BUILD_ID' | extract('Labels' | extract(inspect_lreg.results[inspect_idx].stdout | default('{"Labels":{}}',true) | from_json)) | default('NB',true)) not in (inspect_r.results[inspect_idx].stdout | default('[{"Config":{"Labels":{}}}]',true) | from_json | map(attribute='Config') | map(attribute='Labels') | map(attribute='BUILD_ID') | map('default','NC',true))
-      loop: "{{ inspect_l.results }}"
-      loop_control:
-        loop_var: inspect
-        index_var: inspect_idx
-        label: "{{ inspect.item.key }}"
+    - name: Skopeo copy images
+      shell:
+        cmd: |
+          nohup bash -c '
+            {% for inspect in inspect_l.results %}
+              {% if ((inspect.rc==0) and (inspect.stdout | from_json | map(attribute='Config') | map(attribute='Labels') | map(attribute='BUILD_ID') | map('default','NB',true) | difference(inspect_r.results[loop.index0].stdout | default('[{"Config":{"Labels":{}}}]',true) | from_json | map(attribute='Config') | map(attribute='Labels') | map(attribute='BUILD_ID') | map('default','NC',true)) | length > 0)) or ((inspect.rc!=0) and (('BUILD_ID' | extract('Labels' | extract(inspect_lreg.results[loop.index0].stdout | default('{"Labels":{}}',true) | from_json)) | default('NB',true)) not in (inspect_r.results[loop.index0].stdout | default('[{"Config":{"Labels":{}}}]',true) | from_json | map(attribute='Config') | map(attribute='Labels') | map(attribute='BUILD_ID') | map('default','NC',true)))) %}
+                (
+                  for i in { 1..{{ skopeo_copy_retries }} }; do
+                    skopeo copy {{ skopeo_copy_options }} --src-tls-verify=false --dest-daemon-host=http://{{ local_daemon_url }} {% if inspect.rc==0 %}docker-daemon:{{ inspect.item.key }}{% else %}docker://{{ inspect.item.key }}{% endif %} docker-daemon:{{ inspect.item.key }} && exit 0
+                    sleep {{ skopeo_copy_delay }}
+                  done
+                  echo "Error: Retry Timeout"
+                ) &
+              {% endif %}
+            {% endfor %}
+            wait
+          ' >> >(stdbuf -oL tr '\r' '\n' >> /tmp/{{ wl_namespace }}-{{ inventory_hostname }}-skopeo-progress.logs) 2>&1 &
+          echo $!
+          disown
+        executable: /bin/bash
+      environment:
+        ALL_PROXY: ""
+        all_proxy: ""
+      register: copy_process
+      delegate_to: localhost
+
+    - name: Streaming skopeo copy progress
+      shell:
+        cmd: |
+          echo "nice -n 19 tail -f --pid={{ copy_process.stdout }} /tmp/{{ wl_namespace }}-{{ inventory_hostname }}-skopeo-progress.logs | stdbuf -oL sed 's|^|{{ inventory_hostname }}: |'" > /tmp/streaming-console
+        executable: /bin/bash
+      delegate_to: localhost
+      no_log: true
+
+    - name: Wait until skopeo copy completes
+      shell:
+        cmd: |
+          nice -n 19 tail -f --pid={{ copy_process.stdout }} /dev/null
+          [ -e /tmp/{{ wl_namespace }}-{{ inventory_hostname }}-skopeo-progress.logs ] || exit 3
+          ! grep -q -E 'FATA\[[0-9]*\]|level=fatal|Error:' /tmp/{{ wl_namespace }}-{{ inventory_hostname }}-skopeo-progress.logs
+        executable: /bin/bash
+      delegate_to: localhost
       no_log: true
 
     - name: wait for docker images to be ready
@@ -93,15 +115,15 @@
           '
         executable: /bin/bash
       ignore_errors: true
-      become: false
 
   always:
 
     - name: cancel port forwarding
       shell:
         cmd: |
-          ssh -4 -p {{ ansible_port | default(22) }} {{ ansible_user }}@{{ ansible_host }} -i {{ ansible_private_key_file }} -O cancel -L {{ local_daemon_url }}:/var/run/docker.sock > /dev/null 2>&1
+          ssh -4 -p {{ ansible_port | default(22) }} {{ ansible_user }}@{{ ansible_host }} {% if ansible_private_key_file is defined %}-i {{ ansible_private_key_file }}{% endif %} -O cancel -L {{ local_daemon_url }}:/var/run/docker.sock > /dev/null 2>&1
         executable: /bin/bash
       delegate_to: localhost
-      become: false
+      ignore_errors: true
 
+  become: false
